export const STS_INPUT_MODELS_DATA = [
  { code: "afr", name: "Afrikaans" },
  { code: "amh", name: "Amharic" },
  { code: "arb", name: "Modern Standard Arabic" },
  { code: "ary", name: "Moroccan Arabic" },
  { code: "arz", name: "Egyptian Arabic" },
  { code: "asm", name: "Assamese" },
  { code: "ast", name: "Asturian" },
  { code: "azj", name: "North Azerbaijani" },
  { code: "bel", name: "Belarusian" },
  { code: "ben", name: "Bengali" },
  { code: "bos", name: "Bosnian" },
  { code: "bul", name: "Bulgarian" },
  { code: "cat", name: "Catalan" },
  { code: "ceb", name: "Cebuano" },
  { code: "ces", name: "Czech" },
  { code: "ckb", name: "Central Kurdish" },
  { code: "cmn", name: "Mandarin Chinese" },
  { code: "cym", name: "Welsh" },
  { code: "dan", name: "Danish" },
  { code: "deu", name: "German" },
  { code: "ell", name: "Greek" },
  { code: "eng", name: "English" },
  { code: "est", name: "Estonian" },
  { code: "eus", name: "Basque" },
  { code: "fin", name: "Finnish" },
  { code: "fra", name: "French" },
  { code: "fuv", name: "Nigerian Fulfulde" },
  { code: "gaz", name: "West Central Oromo" },
  { code: "gle", name: "Irish" },
  { code: "glg", name: "Galician" },
  { code: "guj", name: "Gujarati" },
  { code: "heb", name: "Hebrew" },
  { code: "hin", name: "Hindi" },
  { code: "hrv", name: "Croatian" },
  { code: "hun", name: "Hungarian" },
  { code: "hye", name: "Armenian" },
  { code: "ibo", name: "Igbo" },
  { code: "ind", name: "Indonesian" },
  { code: "isl", name: "Icelandic" },
  { code: "ita", name: "Italian" },
  { code: "jav", name: "Javanese" },
  { code: "jpn", name: "Japanese" },
  { code: "kam", name: "Kamba" },
  { code: "kan", name: "Kannada" },
  { code: "kat", name: "Georgian" },
  { code: "kaz", name: "Kazakh" },
  { code: "kea", name: "Kabuverdianu" },
  { code: "khk", name: "Halh Mongolian" },
  { code: "khm", name: "Khmer" },
  { code: "kir", name: "Kyrgyz" },
  { code: "kor", name: "Korean" },
  { code: "lao", name: "Lao" },
  { code: "lit", name: "Lithuanian" },
  { code: "ltz", name: "Luxembourgish" },
  { code: "lug", name: "Ganda" },
  { code: "luo", name: "Luo" },
  { code: "lvs", name: "Standard Latvian" },
  { code: "mai", name: "Maithili" },
  { code: "mal", name: "Malayalam" },
  { code: "mar", name: "Marathi" },
  { code: "mkd", name: "Macedonian" },
  { code: "mlt", name: "Maltese" },
  { code: "mni", name: "Meitei" },
  { code: "mya", name: "Burmese" },
  { code: "nld", name: "Dutch" },
  { code: "nno", name: "Norwegian Nynorsk" },
  { code: "nob", name: "Norwegian Bokmål" },
  { code: "npi", name: "Nepali" },
  { code: "nya", name: "Nyanja" },
  { code: "oci", name: "Occitan" },
  { code: "ory", name: "Odia" },
  { code: "pan", name: "Punjabi" },
  { code: "pbt", name: "Southern Pashto" },
  { code: "pes", name: "Western Persian" },
  { code: "pol", name: "Polish" },
  { code: "por", name: "Portuguese" },
  { code: "ron", name: "Romanian" },
  { code: "rus", name: "Russian" },
  { code: "slk", name: "Slovak" },
  { code: "slv", name: "Slovenian" },
  { code: "sna", name: "Shona" },
  { code: "snd", name: "Sindhi" },
  { code: "som", name: "Somali" },
  { code: "spa", name: "Spanish" },
  { code: "srp", name: "Serbian" },
  { code: "swe", name: "Swedish" },
  { code: "swh", name: "Swahili" },
  { code: "tam", name: "Tamil" },
  { code: "tel", name: "Telugu" },
  { code: "tgk", name: "Tajik" },
  { code: "tgl", name: "Tagalog" },
  { code: "tha", name: "Thai" },
  { code: "tur", name: "Turkish" },
  { code: "ukr", name: "Ukrainian" },
  { code: "urd", name: "Urdu" },
  { code: "uzn", name: "Northern Uzbek" },
  { code: "vie", name: "Vietnamese" },
  { code: "xho", name: "Xhosa" },
  { code: "yor", name: "Yoruba" },
  { code: "yue", name: "Cantonese" },
  { code: "zlm", name: "Colloquial Malay" },
  { code: "zsm", name: "Standard Malay" },
  { code: "zul", name: "Zulu" },
];

export const STS_OUTPUT_MODELS_DATA = [
  { code: "arb", name: "Arabic" },
  { code: "ben", name: "Bengali" },
  { code: "cat", name: "Catalan" },
  { code: "ces", name: "Czech" },
  { code: "cmn", name: "Mandarin Chinese" },
  { code: "cym", name: "Welsh" },
  { code: "dan", name: "Danish" },
  { code: "deu", name: "German" },
  { code: "eng", name: "English" },
  { code: "est", name: "Estonian" },
  { code: "fin", name: "Finnish" },
  { code: "fra", name: "French" },
  { code: "hin", name: "Hindi" },
  { code: "ind", name: "Indonesian" },
  { code: "ita", name: "Italian" },
  { code: "jpn", name: "Japanese" },
  { code: "kor", name: "Korean" },
  { code: "mlt", name: "Maltese" },
  { code: "nld", name: "Dutch" },
  { code: "pes", name: "Persian" },
  { code: "pol", name: "Polish" },
  { code: "por", name: "Portuguese" },
  { code: "ron", name: "Romanian" },
  { code: "rus", name: "Russian" },
  { code: "slk", name: "Slovak" },
  { code: "spa", name: "Spanish" },
  { code: "swe", name: "Swedish" },
  { code: "swh", name: "Swahili" },
  { code: "tel", name: "Telugu" },
  { code: "tgl", name: "Tagalog" },
  { code: "tha", name: "Thai" },
  { code: "tur", name: "Turkish" },
  { code: "urd", name: "Urdu" },
  { code: "ukr", name: "Ukrainian" },
  { code: "uzn", name: "Uzbek" },
  { code: "vie", name: "Vietnamese" },
];
